#!/usr/bin/env ruby
oldrev, newrev = ARGV

def run(cmd)
  exit($?.exitstatus) unless system "umask 002 && #{cmd}"
end

NODE_ENV = ENV['NODE_ENV'] || 'production'

run "npm install"
run "npm run build"

# clear cached assets (unversioned/ignored files)
# run "git clean -x -f -- public/stylesheets public/javascripts"

# clean unversioned files from vendor/plugins (e.g. old submodules)
# run "git clean -d -f -- vendor/plugins"
